[package]
name = "minilet-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
minilet-syntax = { path = "../minilet-syntax" }
minilet-utils = { path = "../minilet-utils" }
parcom.workspace = true

[dev-dependencies]
pollster.workspace = true
